// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd9KFcBa4vuVWgPaJIorwgHjcEclBHaxs',
    appId: '1:95016278438:web:643a4d4bfabee164e31767',
    messagingSenderId: '95016278438',
    projectId: 'lun-talabatkom',
    authDomain: 'lun-talabatkom.firebaseapp.com',
    storageBucket: 'lun-talabatkom.appspot.com',
    measurementId: 'G-X8HB4BYY5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC53S58rmd-fIjckhkRwavBoqzOaFjAiQI',
    appId: '1:95016278438:android:35138655e0343308e31767',
    messagingSenderId: '95016278438',
    projectId: 'lun-talabatkom',
    storageBucket: 'lun-talabatkom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWmOESCK6a_ydf2rIHCPciUPJzfdzCfoA',
    appId: '1:95016278438:ios:01b3cc7c42fb0d3be31767',
    messagingSenderId: '95016278438',
    projectId: 'lun-talabatkom',
    storageBucket: 'lun-talabatkom.appspot.com',
    iosClientId: '95016278438-iotr91f6on6fed5ugs33co76dqi36k3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunTalabatyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWmOESCK6a_ydf2rIHCPciUPJzfdzCfoA',
    appId: '1:95016278438:ios:01b3cc7c42fb0d3be31767',
    messagingSenderId: '95016278438',
    projectId: 'lun-talabatkom',
    storageBucket: 'lun-talabatkom.appspot.com',
    iosClientId: '95016278438-iotr91f6on6fed5ugs33co76dqi36k3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunTalabatyApp',
  );
}
